#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except SSH (22), HTTP (80), and HTTPS (443)

apt-get update -y
apt-get install -y ufw

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw --force enable
