#!/usr/bin/env bash
# Installs nginx server

apt-get update
apt-get -y install nginx ufw
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
service nginx start
