#!/usr/bin/env bash
# Installs Nginx and configures a 301 redirect from /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" | tee /var/www/html/index.nginx-debian.html > /dev/null

sed -i '/listen 80 default_server;/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx start
service nginx restart
